name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install XFCE4 Desktop
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies

    - name: Install XRDP
      run: |
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure XRDP for XFCE
      run: |
        echo "xfce4-session" > ~/.xsession
        sudo sed -i 's/\/etc\/X11\/Xsession/\/usr\/bin\/xfce4-session/g' /etc/xrdp/startwm.sh

    - name: Set Password for Runner User
      run: echo "runner:p@ssw0rd!" | sudo chpasswd

    - name: Download Playit.gg
      run: |
        curl -L https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64 -o playit
        chmod +x playit

    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        ./playit --secret $PLAYIT_AUTH_KEY &
        sleep 10  # Give some time for Playit to start
        ./playit tunnel create --port 3389 --protocol tcp

    - name: Keep the GitHub Action Runner Alive
      run: sleep 11800  # Adjust the duration based on your needs
