name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install XFCE4 Desktop
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies

    - name: Install XRDP
      run: |
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure XRDP for XFCE
      run: |
        echo "xfce4-session" > ~/.xsession
        sudo sed -i 's/\/etc\/X11\/Xsession/\/usr\/bin\/xfce4-session/g' /etc/xrdp/startwm.sh

    - name: Set Password for Runner User
      run: echo "runner:P@ssw0rd!" | sudo chpasswd

    - name: Ensure Home Directory
      run: |
        sudo mkdir -p /home/runner
        sudo chown runner:runner /home/runner

    - name: Download Ngrok
      run: curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz

    - name: Extract Ngrok
      run: tar -xzf ngrok.tgz

    - name: Auth Ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: ./ngrok tcp 3389
